### ISSUE TITLE
endianness in kernel/bitcount

### ISSUE THREAD

**Issue by flopsi** [tacle/tacle-bench#12]
The function bitcount_btbl_bitcnt contains an issue concerning endianness.

A potential fix using a define "BIGENDIAN" can be found in the patch:
[0006-fix-issue-with-endianness-and-missing-semicolon-for-.txt](https://github.com/tacle/tacle-bench/files/1943328/0006-fix-issue-with-endianness-and-missing-semicolon-for-.txt)

**Comment by schoeberl** [comment]
I can apply your patch. But if you would do it as a GitHub pull request your name would be in the history.

**Comment by flopsi** [comment]
The patch is only a proposal and does not represent a complete solution. Are such defines desired in the benchmarks? How should the defines be handled? Were should they be documented? How should they be integrated into the build system?

I can help with this, but this was not my initial intention here. I just wanted to point these issues out.

**Comment by schoeberl** [comment]
Ok, I understand. You proposal then would need a define at compilation, otherwise it would not compile, right? Maybe a default define that can be overridden. But this still is very much a workaround :-(

My comment on pull request was not just for this patch, but in general to have the history who contributed what. Looks like this gets lost when I apply your patch with git apply.
